ckpt_name: checkpoint_improve-0_epoch-19
deploy_check_max_round: 10
deploy_port: 8021
log_dir: /home/ruiyiwan/sotopia-llm/llm_self_train/logs/base-sft-round-2
tmp_dir: /home/ruiyiwan/sotopia-llm/llm_self_train/tmp/base-sft-round-2
