CUDA_VISIBLE_DEVICES=0 deepspeed src/train_bash.py \
    --stage rm \
    --model_name_or_path mistralai/Mistral-7B-v0.1 \
    --do_train \
    --dataset comparison_gpt4_en \
    --template default \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --resume_lora_training False \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 10 \
    --learning_rate 1e-6 \
    --num_train_epochs 1.0 \
    --plot_loss \
    --bf16 \
    --cache_dir ./model_cache \
    --overwrite_cache \
    --output_dir ./mistral-7b-rm_cache \
    --overwrite_output_dir \
    --use_auth_token True \
    --wandb_token "99caa13ec9552adf0e92e5c30021307ce3cf7fa4" \
    --hf_auth_token "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" \
    --deepspeed ./deepspeed_config_s2.json \
    --gradient_checkpointing True
