deepspeed src/train_bash.py \
    --stage sft \
    --model_name_or_path meta-llama/Llama-2-13b-hf \
    --dataset fastchat-sft \
    --dataset_dir ./data/ \
    --val_size 0.1 \
    --cutoff_len 2110 \
    --template llama2-sotopia \
    --wandb_project "llama-factory-sft" \
    --wandb_tags "['llama-2-13b-hf-2k']" \
    --use_fast_tokenizer False \
    --do_train \
    --num_train_epochs 15.0 \
    --per_device_train_batch_size 8 \
    --gradient_accumulation_steps 8 \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --learning_rate 5e-5 \
    --lr_scheduler_type cosine \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --quantization_bit 4 \
    --quantization_type nf4 \
    --double_quantization True \
    --flash_attn True \
    --gradient_checkpointing True \
    --bf16 True \
    --cache_dir ./model_cache \
    --overwrite_cache \
    --output_dir ./llama2-13b-sft_cache \
    --overwrite_output_dir \
    --logging_steps 1 \
    --evaluation_strategy "steps" \
    --per_device_eval_batch_size 32 \
    --eval_accumulation_steps 32 \
    --save_strategy "epoch" \
    --save_total_limit 5 \
    --use_auth_token True \
    --wandb_token "99caa13ec9552adf0e92e5c30021307ce3cf7fa4" \
    --hf_auth_token "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" \
    --deepspeed ./deepspeed_config_s2.json

    # --dataset alpaca_gpt4_en \