deepspeed src/train_bash.py \
    --stage sft \
    --model_name_or_path meta-llama/Llama-2-13b-hf \
    --dataset sotopia_easy_sft \
    --dataset_dir ./data/ \
    --template llama2-sotopia \
    --use_fast_tokenizer False \
    --do_train \
    --cutoff_len 4096 \
    --finetuning_type lora \
    --lora_target q_proj,v_proj \
    --cache_dir ./model_cache \
    --quantization_bit 4 \
    --quantization_type nf4 \
    --double_quantization \
    --flash_attn True \
    --gradient_checkpointing True \
    --use_auth_token True \
    --hf_auth_token "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" \
    --output_dir ./llama2-13b-sft_cache \
    --overwrite_cache \
    --overwrite_output_dir \
    --per_device_train_batch_size 8 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine \
    --logging_steps 1 \
    --save_strategy "epoch" \
    --save_total_limit 5 \
    --learning_rate 5e-5 \
    --num_train_epochs 10.0 \
    --plot_loss \
    --bf16 \
    --deepspeed ./deepspeed_config_s2.json \
    --wandb_token "99caa13ec9552adf0e92e5c30021307ce3cf7fa4"

    # --dataset alpaca_gpt4_en \