babel_username: ruiyiwan
ckpt_name: checkpoint-base_epoch_2
deploy_check_max_round: 10
deploy_model_dir: /data/tir/projects/tir6/bisk/ruiyiwan/selftrain/pilot-1/
deploy_port: 8010
deploy_queue_file: /home/ruiyiwan/selftrain_scripts/logs/pilot-1/deploy_queue.txt
experiment_name: pilot-1
generate_gin_file: /home/ruiyiwan/selftrain_scripts/config/generate.gin
log_dir: /home/ruiyiwan/selftrain_scripts/logs/pilot-1
root_dir: /home/ruiyiwan/selftrain_scripts
tmp_dir: /home/ruiyiwan/selftrain_scripts/tmp/pilot-1
